-- Q6 
-- Find all the content creators living in the US who have consistently posted at least 1 video each week of the last month. 
-- Display their username, channel/s they own and their total subscriber count.

-- SOFTWARE/DB USED : MYSQL SERVER (XAMPP) + SQL WORKBENCH

SELECT U.USERNAME, FREQ_CREATOR.CHANNEL_NAME, COUNT(SUB.SUBSCRIPTION_RECORD_ID) AS TOTAL_SUBSCRIPTION
FROM `youtube`.`YOUTUBE_SUBSCRIPTION` SUB RIGHT JOIN
(
	SELECT C.CHANNEL_NAME, C.CHANNEL_ID,  COUNT(DISTINCT(WEEK(V.UPLOAD_DATETIME))) AS ROW_WEEK
	FROM `youtube`.`YOUTUBE_VIDEO` V, `youtube`.`YOUTUBE_CHANNEL` C
	WHERE V.UPLOAD_USER_ID IN(
		SELECT USER_ID FROM `youtube`.`YOUTUBE_USER` 
		WHERE IS_CREATOR = 1 AND Address LIKE '%USA%'
	)
	AND V.CHANNEL_ID = C.CHANNEL_ID
	AND V.UPLOAD_DATETIME BETWEEN DATE_FORMAT(NOW() - INTERVAL 1 MONTH, '%Y-%m-01') AND DATE_FORMAT(NOW() ,'%Y-%m-01')
	GROUP BY  C.CHANNEL_NAME
	HAVING ROW_WEEK = WEEK(LAST_DAY(now() - INTERVAL 1 MONTH)) - WEEK(DATE_FORMAT(CURDATE() - INTERVAL 1 MONTH,'%Y-%m-01')) + 1
) AS FREQ_CREATOR
ON FREQ_CREATOR.CHANNEL_ID = SUB.CHANNEL_ID,
youtube.YOUTUBE_USER U, youtube.YOUTUBE_CHANNEL C
WHERE U.USER_ID = C.USER_ID
AND FREQ_CREATOR.CHANNEL_ID = C.CHANNEL_ID
GROUP BY FREQ_CREATOR.CHANNEL_NAME;


-- Exaplanation
/*
1. In this query, we created a subquery in the FROM clause, the subquery returns a table which is formed by joining YOUTUBE_VIDEO, YOUTUBE_CHANNEL
	Here, we try to find channels for which the creator lives in the US and those channel's have uploaded videos every week of last month.
2. The HAVING clause in this subquery finds the no of weeks in the last nonth and the COUNT(DISTINCT(WEEK(V.UPLOAD_DATETIME))) AS ROW_WEEK gives the no of week a specific Channel has uploaded videos.
3. In the WHERE clause of the subquery we make sure we only perform the above operation on videos of last month. 
4. Then we have right join the YOUTUBE_SUBSCRIPTION table with the subquery table to print the channel name even if it has zero subscriptions
5. Finallly, we have joined it with YOUTUBE_USER & YOUTUBE_CHANNEL to print the username associated with the channel name.
*/


-- DDL & DML commands prerequisite for the above query

CREATE DATABASE youtube;

CREATE TABLE `youtube`.`YOUTUBE_USER` (
    `USER_ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
    `USERNAME` VARCHAR(40) UNIQUE,
    `NAME` VARCHAR(40) NOT NULL,
    `EMAIL` VARCHAR(40) NOT NULL,
    `AGE` INT(3) NOT NULL,
    `ADDRESS` VARCHAR(200) NOT NULL,
    `IS_CREATOR` BOOLEAN NOT NULL DEFAULT FALSE,
    `IS_CONSUMER` BOOLEAN NOT NULL DEFAULT TRUE,
    `JOINING_DATE` DATETIME NOT NULL,
    CHECK (`AGE`>=5),
    PRIMARY KEY (`USER_ID`)
);

CREATE TABLE `youtube`.`YOUTUBE_CHANNEL` (
    `CHANNEL_ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`USER_ID` BIGINT(20),
    `CHANNEL_NAME` VARCHAR(100) NOT NULL,
    `CREATE_DATE` DATETIME NOT NULL,
    `NO_OF_SUBSCRIBERS` BIGINT(20) NOT NULL,
    PRIMARY KEY (`CHANNEL_ID`),
    FOREIGN KEY (`USER_ID`) REFERENCES `youtube`.`YOUTUBE_USER`(`USER_ID`)
);

CREATE TABLE `youtube`.`YOUTUBE_VIDEO` (
    `VIDEO_ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
    `TITLE` VARCHAR(50) NOT NULL,
    `URL` VARCHAR(200) NOT NULL,
    `THUMBNAIL` VARCHAR(200) NOT NULL,
    `CATEGORY` VARCHAR(20) NOT NULL,
    `DURATION` INT(10) NOT NULL,
    `DESCRIPTION` VARCHAR(300) NOT NULL,
    `UPLOAD_DATETIME` DATETIME NOT NULL,
    `IS_TRANSCODING_DONE` BOOLEAN NOT NULL DEFAULT FALSE,
    `CHANNEL_ID` BIGINT,
    `UPLOAD_USER_ID` BIGINT,
    PRIMARY KEY (`VIDEO_ID`),
    FOREIGN KEY (`UPLOAD_USER_ID`) REFERENCES `youtube`.`YOUTUBE_USER`(`USER_ID`),
    FOREIGN KEY (`CHANNEL_ID`) REFERENCES `youtube`.`YOUTUBE_CHANNEL`(`CHANNEL_ID`)
);

CREATE TABLE `youtube`.`YOUTUBE_SPONSOR` (
    `SPONSOR_ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
    `SPONSOR_NAME` VARCHAR(50) NOT NULL,
    `SPONSOR_PHONE_NO` VARCHAR(20) NOT NULL,
    `SPONSOR_EMAIL` VARCHAR(40) NOT NULL,
    `SPONSOR_ADDRESS` VARCHAR(200) NOT NULL,
    `SPONSOR_BANK_ACCOUNT_NO` VARCHAR(100) NOT NULL,
    PRIMARY KEY (`SPONSOR_ID`)
);

CREATE TABLE `youtube`.`YOUTUBE_VIDEO_SPONSOR_MAPPING` (
    `VS_MAPPING_RECORD_ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
    `SPONSORED_AMOUNT` BIGINT(20) NOT NULL,
    `VIDEO_ID` BIGINT(20) NOT NULL,
    `SPONSOR_ID` BIGINT(20) NOT NULL,
    PRIMARY KEY (`VS_MAPPING_RECORD_ID`),
	FOREIGN KEY (`SPONSOR_ID`) REFERENCES `youtube`.`YOUTUBE_SPONSOR`(`SPONSOR_ID`),
    FOREIGN KEY (`VIDEO_ID`) REFERENCES `youtube`.`YOUTUBE_VIDEO`(`VIDEO_ID`)
);

CREATE TABLE `youtube`.`YOUTUBE_LIKES` (
    `USER_ID` BIGINT(20) NOT NULL,
    `VIDEO_ID` BIGINT(20) NOT NULL,
    `LIKE_DATETIME` DATETIME NOT NULL,
	FOREIGN KEY (`USER_ID`) REFERENCES `youtube`.`YOUTUBE_USER`(`USER_ID`),
    FOREIGN KEY (`VIDEO_ID`) REFERENCES `youtube`.`YOUTUBE_VIDEO`(`VIDEO_ID`),
    PRIMARY KEY (`USER_ID`,`VIDEO_ID`)
);

CREATE TABLE `youtube`.`YOUTUBE_HISTORY` (
    `WATCH_TIMESTAMP` TIMESTAMP NOT NULL,
    `USER_ID` BIGINT(20) NOT NULL,
    `VIDEO_ID` BIGINT(20) NOT NULL,
	FOREIGN KEY (`USER_ID`) REFERENCES `youtube`.`YOUTUBE_USER`(`USER_ID`),
    FOREIGN KEY (`VIDEO_ID`) REFERENCES `youtube`.`YOUTUBE_VIDEO`(`VIDEO_ID`),
    PRIMARY KEY (`WATCH_TIMESTAMP`,`USER_ID`,`VIDEO_ID`)
);

CREATE TABLE `youtube`.`YOUTUBE_SUBSCRIPTION` (
    `SUBSCRIPTION_RECORD_ID` BIGINT(20) NOT NULL,
    `IS_PAID_SUBSCRIPTION` BOOLEAN NOT NULL,
    `CHANNEL_ID` BIGINT,
    `USER_ID` BIGINT,
    PRIMARY KEY (`SUBSCRIPTION_RECORD_ID`),
	FOREIGN KEY (`CHANNEL_ID`) REFERENCES `youtube`.`YOUTUBE_CHANNEL`(`CHANNEL_ID`),
    FOREIGN KEY (`USER_ID`) REFERENCES `youtube`.`YOUTUBE_USER`(`USER_ID`)
);

CREATE TABLE `youtube`.`YOUTUBE_KEYWORDS` (
	`KEYWORD_ID` BIGINT(20) AUTO_INCREMENT,
    `KEYWORD_NAME` VARCHAR(50) NOT NULL,
    `CREATION_DATETIME` DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`KEYWORD_ID`)
);


CREATE TABLE `youtube`.`YOUTUBE_KEYWORD_VIDEO_MAPPING` (
    `VIDEO_ID` BIGINT(20) NOT NULL,
    `KEYWORD_ID` BIGINT(20) NOT NULL,
    `ASSIGNED_DATE_TIME` DATETIME NOT NULL,
    FOREIGN KEY (`KEYWORD_ID`) REFERENCES `youtube`.`YOUTUBE_KEYWORDS`(`KEYWORD_ID`),
    FOREIGN KEY (`VIDEO_ID`) REFERENCES `youtube`.`YOUTUBE_VIDEO`(`VIDEO_ID`),
    PRIMARY KEY (`VIDEO_ID`, `KEYWORD_ID`)
);



CREATE TABLE `youtube`.`YOUTUBE_COMMENTS` (
    `COMMENT_ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
    `TEXT` VARCHAR(300) NOT NULL,
    `COMMENT_DATETIME` DATETIME NOT NULL,
    `SENTIMENTS` DECIMAL(3,2) NOT NULL,
    `NO_OF_LIKES` BIGINT(20) NOT NULL,
    `VIDEO_ID` BIGINT(20) NOT NULL,
    `USER_ID` BIGINT(20) NOT NULL,
    PRIMARY KEY (`COMMENT_ID`),
	FOREIGN KEY (`USER_ID`) REFERENCES `youtube`.`YOUTUBE_USER`(`USER_ID`),
    FOREIGN KEY (`VIDEO_ID`) REFERENCES `youtube`.`YOUTUBE_VIDEO`(`VIDEO_ID`)
);


-- INSERT USERS
INSERT INTO youtube.YOUTUBE_USER (USERNAME, NAME, EMAIL, AGE,  ADDRESS, IS_CREATOR, IS_CONSUMER, JOINING_DATE)
VALUES ('john123', 'John Doe', 'john.doe@example.com', 15 ,  '123 Main Street, Anytown, UK', true, true, '2022-01-01 00:00:00');

INSERT INTO youtube.YOUTUBE_USER (USERNAME, NAME, EMAIL, AGE, ADDRESS, IS_CREATOR, IS_CONSUMER, JOINING_DATE)
VALUES ('jane456', 'Jane Smith', 'jane.smith@example.com', 35, '456 Maple Avenue, Anytown, UK', true, true, '2022-02-01 00:00:00');

INSERT INTO youtube.YOUTUBE_USER (USERNAME, NAME, EMAIL, AGE, ADDRESS, IS_CREATOR, IS_CONSUMER, JOINING_DATE)
VALUES ('bob789', 'Bob Johnson', 'bob.johnson@example.com', 18, '789 Oak Street, Anytown, UK', true, true, '2022-03-01 00:00:00');

INSERT INTO youtube.YOUTUBE_USER (USERNAME, NAME, EMAIL, AGE, ADDRESS, IS_CREATOR, IS_CONSUMER, JOINING_DATE)
VALUES ('johndoe', 'John Doe', 'johndoe@example.com', 28, '123 Main St, Anytown UK', TRUE, true, '2022-01-01 10:00:00');

INSERT INTO youtube.YOUTUBE_USER (USERNAME, NAME, EMAIL, AGE, ADDRESS, IS_CREATOR, IS_CONSUMER, JOINING_DATE)
VALUES ('janedoe', 'Jane Doe', 'janedoe@example.com', 24, '456 Main St, Anytown USA', true, true, '2022-01-02 11:00:00');

INSERT INTO youtube.YOUTUBE_USER (USERNAME, NAME, EMAIL, AGE, ADDRESS, IS_CREATOR, IS_CONSUMER, JOINING_DATE)
VALUES ('bobsmith', 'Bob Smith', 'bobsmith@example.com', 45, '789 Main St, Anytown USA', true, TRUE, '2022-01-03 12:00:00');

INSERT INTO youtube.YOUTUBE_USER (USERNAME, NAME, EMAIL, AGE, ADDRESS, IS_CREATOR, IS_CONSUMER, JOINING_DATE)
VALUES ('alicesmith', 'Alice Smith', 'alicesmith@example.com', 31, '555 Oak St, Anytown USA', TRUE, true, '2022-01-04 13:00:00');

INSERT INTO youtube.YOUTUBE_USER (USERNAME, NAME, EMAIL, AGE, ADDRESS, IS_CREATOR, IS_CONSUMER, JOINING_DATE)
VALUES ('sarahjones', 'Sarah Jones', 'sarahjones@example.com', 19, '777 Maple St, Anytown USA', true, TRUE, '2022-01-05 14:00:00');

INSERT INTO youtube.YOUTUBE_USER (USERNAME, NAME, EMAIL, AGE, ADDRESS, IS_CREATOR, IS_CONSUMER, JOINING_DATE)
VALUES ('davidlee', 'David Lee', 'davidlee@example.com', 52, '999 Pine St, Anytown USA', true, TRUE, '2022-01-06 15:00:00');

INSERT INTO youtube.YOUTUBE_USER (USERNAME, NAME, EMAIL, AGE, ADDRESS, IS_CREATOR, IS_CONSUMER, JOINING_DATE)
VALUES ('lucybrown', 'Lucy Brown', 'lucybrown@example.com', 28, '123 Elm St, Anytown USA', TRUE, true, '2022-01-07 16:00:00');

INSERT INTO youtube.YOUTUBE_USER (USERNAME, NAME, EMAIL, AGE, ADDRESS, IS_CREATOR, IS_CONSUMER, JOINING_DATE)
VALUES ('brianmiller', 'Brian Miller', 'brianmiller@example.com', 40, '456 Oak St, Anytown USA', FALSE, TRUE, '2022-01-08 17:00:00');

INSERT INTO youtube.YOUTUBE_USER (USERNAME, NAME, EMAIL, AGE, ADDRESS, IS_CREATOR, IS_CONSUMER, JOINING_DATE)
VALUES ('karenwhite', 'Karen White', 'karenwhite@example.com', 22, '789 Elm St, Anytown USA', FALSE, TRUE, '2022-01-09 18:00:00');

INSERT INTO youtube.YOUTUBE_USER (USERNAME, NAME, EMAIL, AGE, ADDRESS, IS_CREATOR, IS_CONSUMER, JOINING_DATE)
VALUES ('marvelEntertainment', 'Marvel Entertainment', 'marvelEntertainment@example.com', 22, '789 Elm St, Anytown USA', true, TRUE, '2022-01-09 18:00:00');

INSERT INTO youtube.YOUTUBE_USER (USERNAME, NAME, EMAIL, AGE, ADDRESS, IS_CREATOR, IS_CONSUMER, JOINING_DATE)
VALUES ('taylorSwift', 'Taylor Swift', 'taylorSwiftVEVEO@example.com', 22, '789 Elm St, Anytown USA', true, TRUE, '2022-01-09 18:00:00');

-- INSERET CHANNELS
INSERT INTO youtube.YOUTUBE_CHANNEL (USER_ID, CHANNEL_NAME, CREATE_DATE, NO_OF_SUBSCRIBERS)
VALUES (1, 'JohnDoeVlogs', '2022-01-01 10:00:00', 0);

INSERT INTO youtube.YOUTUBE_CHANNEL (USER_ID, CHANNEL_NAME, CREATE_DATE, NO_OF_SUBSCRIBERS)
VALUES (2, 'JaneDoeGaming', '2022-01-02 11:00:00', 0);

INSERT INTO youtube.YOUTUBE_CHANNEL (USER_ID, CHANNEL_NAME, CREATE_DATE, NO_OF_SUBSCRIBERS)
VALUES (3, 'BobSmithReviews', '2022-01-03 12:00:00', 0);

INSERT INTO youtube.YOUTUBE_CHANNEL (USER_ID, CHANNEL_NAME, CREATE_DATE, NO_OF_SUBSCRIBERS)
VALUES (4, 'AliceSmithMusic', '2022-01-04 13:00:00', 0);

INSERT INTO youtube.YOUTUBE_CHANNEL (USER_ID, CHANNEL_NAME, CREATE_DATE, NO_OF_SUBSCRIBERS)
VALUES (5, 'SarahJonesDIY', '2022-01-05 14:00:00', 0);

INSERT INTO youtube.YOUTUBE_CHANNEL (USER_ID, CHANNEL_NAME, CREATE_DATE, NO_OF_SUBSCRIBERS)
VALUES (6, 'DavidLeeFitness', '2022-01-06 15:00:00', 0);

INSERT INTO youtube.YOUTUBE_CHANNEL (USER_ID, CHANNEL_NAME, CREATE_DATE, NO_OF_SUBSCRIBERS)
VALUES (7, 'LucyBrownCooking', '2022-01-07 16:00:00', 0);

INSERT INTO youtube.YOUTUBE_CHANNEL (USER_ID, CHANNEL_NAME, CREATE_DATE, NO_OF_SUBSCRIBERS)
VALUES (8, 'BrianMillerTravel', '2022-01-08 17:00:00', 0);

INSERT INTO youtube.YOUTUBE_CHANNEL (USER_ID, CHANNEL_NAME, CREATE_DATE, NO_OF_SUBSCRIBERS)
VALUES (9, 'KarenWhiteArt', '2022-01-09 18:00:00', 0);

INSERT INTO youtube.YOUTUBE_CHANNEL (USER_ID, CHANNEL_NAME, CREATE_DATE, NO_OF_SUBSCRIBERS)
VALUES (10, 'MaxJacksonFitness', '2022-01-10 19:00:00', 0);

INSERT INTO youtube.YOUTUBE_CHANNEL (USER_ID, CHANNEL_NAME, CREATE_DATE, NO_OF_SUBSCRIBERS)
VALUES (13, 'Marvel Fans Channel', '2022-01-10 19:00:00', 0);

INSERT INTO youtube.YOUTUBE_CHANNEL (USER_ID, CHANNEL_NAME, CREATE_DATE, NO_OF_SUBSCRIBERS)
VALUES (14, 'Taylor Swift VEVO', '2022-01-10 19:00:00', 0);

INSERT INTO youtube.YOUTUBE_CHANNEL (USER_ID, CHANNEL_NAME, CREATE_DATE, NO_OF_SUBSCRIBERS)
VALUES (14, 'Taylor Swift Private', '2022-01-10 19:00:00', 0);

-- INSERT VIDEOS
INSERT INTO youtube.YOUTUBE_VIDEO (TITLE, URL, THUMBNAIL, CATEGORY, DURATION, DESCRIPTION, UPLOAD_DATETIME, IS_TRANSCODING_DONE, CHANNEL_ID, UPLOAD_USER_ID)
VALUES ('Funny Cat Video', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', 'https://i.ytimg.com/vi/dQw4w9WgXcQ/maxresdefault.jpg', 'Informational', 120, 'Watch this hilarious cat video!', '2023-02-24 13:00:00', TRUE, 2, 6);

INSERT INTO youtube.YOUTUBE_VIDEO (TITLE, URL, THUMBNAIL, CATEGORY, DURATION, DESCRIPTION, UPLOAD_DATETIME, IS_TRANSCODING_DONE, CHANNEL_ID, UPLOAD_USER_ID)
VALUES ('Cooking Tutorial: Homemade Pizza', 'https://www.youtube.com/watch?v=VH-2QbzRJk4', 'https://i.ytimg.com/vi/VH-2QbzRJk4/maxresdefault.jpg', 'Informational', 3600, 'Learn how to make delicious homemade pizza from scratch!', '2023-02-22 10:30:00', FALSE, 5, 9);

INSERT INTO youtube.YOUTUBE_VIDEO (TITLE, URL, THUMBNAIL, CATEGORY, DURATION, DESCRIPTION, UPLOAD_DATETIME, IS_TRANSCODING_DONE, CHANNEL_ID, UPLOAD_USER_ID)
VALUES ('Top 10 Video Games of All Time', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', 'https://i.ytimg.com/vi/dQw4w9WgXcQ/maxresdefault.jpg', 'Informational', 1800, 'Check out our list of the best video games ever made!', '2023-02-20 15:45:00', TRUE, 3, 3);

INSERT INTO youtube.YOUTUBE_VIDEO (TITLE, URL, THUMBNAIL, CATEGORY, DURATION, DESCRIPTION, UPLOAD_DATETIME, IS_TRANSCODING_DONE, CHANNEL_ID, UPLOAD_USER_ID)
VALUES ('Learn to Dance: Salsa Tutorial', 'https://www.youtube.com/watch?v=h8Zb2g9XjGQ', 'https://i.ytimg.com/vi/h8Zb2g9XjGQ/maxresdefault.jpg', 'Informational', 2400, 'Get your hips moving with this beginner-friendly salsa dance tutorial!', '2023-02-19 12:15:00', FALSE, 4, 1);

INSERT INTO youtube.YOUTUBE_VIDEO (TITLE, URL, THUMBNAIL, CATEGORY, DURATION, DESCRIPTION, UPLOAD_DATETIME, IS_TRANSCODING_DONE, CHANNEL_ID, UPLOAD_USER_ID)
VALUES ('Travel Vlog: Exploring Tokyo', 'https://www.youtube.com/watch?v=DKOvOxn--MI', 'https://i.ytimg.com/vi/DKOvOxn--MI/maxresdefault.jpg', 'Informational', 4800, 'Join us as we explore the vibrant streets of Tokyo!', '2023-02-17 09:00:00', TRUE, 1, 4);

INSERT INTO youtube.YOUTUBE_VIDEO (TITLE, URL, THUMBNAIL, CATEGORY, DURATION, DESCRIPTION, UPLOAD_DATETIME, IS_TRANSCODING_DONE, CHANNEL_ID, UPLOAD_USER_ID)
VALUES ('Marvel Fanfiction Part 1', 'https://www.youtube.com/watch?v=DKOvOxn--MI', 'https://i.ytimg.com/vi/DKOvOxn--MI/maxresdefault.jpg', 'Informational', 4800, 'Fanfiction Part 1!', '2023-02-17 09:00:00', TRUE, 11, 13);

INSERT INTO youtube.YOUTUBE_VIDEO (TITLE, URL, THUMBNAIL, CATEGORY, DURATION, DESCRIPTION, UPLOAD_DATETIME, IS_TRANSCODING_DONE, CHANNEL_ID, UPLOAD_USER_ID)
VALUES ('Marvel Fanfiction Part 2', 'https://www.youtube.com/watch?v=DKOvOxn--MI', 'https://i.ytimg.com/vi/DKOvOxn--MI/maxdresdefault.jpg', 'Informational', 4800, 'Fanfiction Part 2!', '2023-02-17 09:00:00', TRUE, 11, 13);

INSERT INTO youtube.YOUTUBE_VIDEO (TITLE, URL, THUMBNAIL, CATEGORY, DURATION, DESCRIPTION, UPLOAD_DATETIME, IS_TRANSCODING_DONE, CHANNEL_ID, UPLOAD_USER_ID)
VALUES ('Marvel Fanfiction Part 3', 'https://www.youtube.com/watch?v=DKOvOxn--MI', 'https://i.ytimg.com/vi/DKOvOxn--MI/maxdresdefault.jpg', 'Informational', 4800, 'Fanfiction Part !', '2023-02-17 09:00:00', TRUE, 11, 13);

INSERT INTO youtube.YOUTUBE_VIDEO (TITLE, URL, THUMBNAIL, CATEGORY, DURATION, DESCRIPTION, UPLOAD_DATETIME, IS_TRANSCODING_DONE, CHANNEL_ID, UPLOAD_USER_ID)
VALUES ('Marvel Fanfiction Part 4', 'https://www.youtube.com/watch?v=DKOvOxn--MI', 'https://i.ytimg.com/vi/DKOvOxn--MI/maxdresdefault.jpg', 'Informational', 4800, 'Fanfiction Part !', '2023-02-17 09:00:00', TRUE, 11, 13);

INSERT INTO youtube.YOUTUBE_VIDEO (TITLE, URL, THUMBNAIL, CATEGORY, DURATION, DESCRIPTION, UPLOAD_DATETIME, IS_TRANSCODING_DONE, CHANNEL_ID, UPLOAD_USER_ID)
VALUES ('Marvel Fanfiction Part 5', 'https://www.youtube.com/watch?v=DKOvOxn--MI', 'https://i.ytimg.com/vi/DKOvOxn--MI/maxdresdefault.jpg', 'Informational', 4800, 'Fanfiction Part !', '2023-02-17 09:00:00', TRUE, 11, 13);

INSERT INTO youtube.YOUTUBE_VIDEO (TITLE, URL, THUMBNAIL, CATEGORY, DURATION, DESCRIPTION, UPLOAD_DATETIME, IS_TRANSCODING_DONE, CHANNEL_ID, UPLOAD_USER_ID)
VALUES ('Love Story', 'https://www.youtube.com/watch?v=DKOvOdn--MI', 'https://i.ytimg.com/vi/DKOvOxn--MI/mindresdefault.jpg', 'Informational', 4800, 'Love Story !', '2023-01-01 09:00:00', TRUE, 12, 14);

INSERT INTO youtube.YOUTUBE_VIDEO (TITLE, URL, THUMBNAIL, CATEGORY, DURATION, DESCRIPTION, UPLOAD_DATETIME, IS_TRANSCODING_DONE, CHANNEL_ID, UPLOAD_USER_ID)
VALUES ('Everything has changed', 'https://www.youtube.com/watch?v=DKdcvOdn--MI', 'https://i.ytimg.com/vi/DKOvOxn--MI/mindresdefault.jpg', 'Informational', 4800, 'Everything has changed !', '2023-01-08 09:00:00', TRUE, 12, 14);

INSERT INTO youtube.YOUTUBE_VIDEO (TITLE, URL, THUMBNAIL, CATEGORY, DURATION, DESCRIPTION, UPLOAD_DATETIME, IS_TRANSCODING_DONE, CHANNEL_ID, UPLOAD_USER_ID)
VALUES ('Anti Hero', 'https://www.youtube.com/watch?v=DKdcsfdn--MI', 'https://i.ytimg.com/vi/DKOvOsdsd--MI/mindresdefault.jpg', 'Informational', 4800, 'Anti Hero!', '2023-01-15 09:00:00', TRUE, 12, 14);

INSERT INTO youtube.YOUTUBE_VIDEO (TITLE, URL, THUMBNAIL, CATEGORY, DURATION, DESCRIPTION, UPLOAD_DATETIME, IS_TRANSCODING_DONE, CHANNEL_ID, UPLOAD_USER_ID)
VALUES ('Delicate', 'https://www.youtube.com/watch?v=DKdddffdn--MI', 'https://i.ytimg.com/vi/DKOvOssd--MI/mindresdefault.jpg', 'Informational', 4800, 'Delicate', '2023-01-22 09:00:00', TRUE, 12, 14);

INSERT INTO youtube.YOUTUBE_VIDEO (TITLE, URL, THUMBNAIL, CATEGORY, DURATION, DESCRIPTION, UPLOAD_DATETIME, IS_TRANSCODING_DONE, CHANNEL_ID, UPLOAD_USER_ID)
VALUES ('Blank Space', 'https://www.youtube.com/watch?dsdKdcsfdn--MI', 'https://i.ytimg.com/vi/DKOsdssdsd--MI/mindresdefault.jpg', 'Informational', 4800, 'Blank Space', '2023-01-29 09:00:00', TRUE, 12, 14);

INSERT INTO youtube.YOUTUBE_VIDEO (TITLE, URL, THUMBNAIL, CATEGORY, DURATION, DESCRIPTION, UPLOAD_DATETIME, IS_TRANSCODING_DONE, CHANNEL_ID, UPLOAD_USER_ID) 
VALUES ('How to Cook Pasta', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', 'https://i.ytimg.com/vi/dQw4w9WgXcQ/maxresdefault.jpg', 'Informational', 1200, 'Learn how to cook pasta in 20 minutes!', '2023-02-26 14:30:00', 1, 3, 7);

INSERT INTO youtube.YOUTUBE_VIDEO (TITLE, URL, THUMBNAIL, CATEGORY, DURATION, DESCRIPTION, UPLOAD_DATETIME, IS_TRANSCODING_DONE, CHANNEL_ID, UPLOAD_USER_ID) 
VALUES ('Cute Cat Video', 'https://www.youtube.com/watch?v=3JvNlGxpgdA', 'https://i.ytimg.com/vi/3JvNlGxpgdA/maxresdefault.jpg', 'Informational', 300, 'Watch this adorable cat playing with a toy!', '2023-02-25 10:00:00', 1, 1, 9);

INSERT INTO youtube.YOUTUBE_VIDEO (TITLE, URL, THUMBNAIL, CATEGORY, DURATION, DESCRIPTION, UPLOAD_DATETIME, IS_TRANSCODING_DONE, CHANNEL_ID, UPLOAD_USER_ID) 
VALUES ('Funny Prank Compilation', 'https://www.youtube.com/watch?v=6FOUqQt3Kg0', 'https://i.ytimg.com/vi/6FOUqQt3Kg0/maxresdefault.jpg', 'Informational', 1800, 'Watch these hilarious pranks that will make you laugh out loud!', '2023-02-24 16:15:00', 1, 8, 4);

INSERT INTO youtube.YOUTUBE_VIDEO (TITLE, URL, THUMBNAIL, CATEGORY, DURATION, DESCRIPTION, UPLOAD_DATETIME, IS_TRANSCODING_DONE, CHANNEL_ID, UPLOAD_USER_ID) 
VALUES ('How to Play Guitar', 'https://www.youtube.com/watch?v=8eXj97stbG8', 'https://i.ytimg.com/vi/8eXj97stbG8/maxresdefault.jpg', 'Informational', 2400, 'Learn how to play guitar in 30 days!', '2023-02-23 12:00:00', 0, 2, 2);

INSERT INTO youtube.YOUTUBE_VIDEO (TITLE, URL, THUMBNAIL, CATEGORY, DURATION, DESCRIPTION, UPLOAD_DATETIME, IS_TRANSCODING_DONE, CHANNEL_ID, UPLOAD_USER_ID) 
VALUES ('Funny Cats Compilation', 'https://www.youtube.com/watch?v=ABkY3b11Ykw', 'https://i.ytimg.com/vi/ABkY3b11Ykw/hqdefault.jpg', 'Informational', 3600, 'Watch these hilarious cats doing silly things!', '2022-11-03 14:25:00', 0, 4, 9);

INSERT INTO youtube.YOUTUBE_VIDEO (TITLE, URL, THUMBNAIL, CATEGORY, DURATION, DESCRIPTION, UPLOAD_DATETIME, IS_TRANSCODING_DONE, CHANNEL_ID, UPLOAD_USER_ID) 
VALUES ('Yoga for Beginners', 'https://www.youtube.com/watch?v=Jno3pZS-sAk', 'https://i.ytimg.com/vi/Jno3pZS-sAk/hqdefault.jpg', 'Informational', 1800, 'Learn the basics of yoga with this easy-to-follow guide.', '2023-01-01 08:00:00', 1, 7, 6);

INSERT INTO youtube.YOUTUBE_VIDEO (TITLE, URL, THUMBNAIL, CATEGORY, DURATION, DESCRIPTION, UPLOAD_DATETIME, IS_TRANSCODING_DONE, CHANNEL_ID, UPLOAD_USER_ID) 
VALUES ('Cooking with Jamie Oliver', 'https://www.youtube.com/watch?v=5RQn5PJNfL4', 'https://i.ytimg.com/vi/5RQn5PJNfL4/hqdefault.jpg', 'Informational', 2700, 'Join celebrity chef Jamie Oliver as he cooks up a storm in the kitchen!', '2022-12-15 17:30:00', 0, 3, 10);

INSERT INTO youtube.YOUTUBE_VIDEO (TITLE, URL, THUMBNAIL, CATEGORY, DURATION, DESCRIPTION, UPLOAD_DATETIME, IS_TRANSCODING_DONE, CHANNEL_ID, UPLOAD_USER_ID) 
VALUES ('Gardening Tips for Spring', 'https://www.youtube.com/watch?v=fz-gsWVi9OU', 'https://i.ytimg.com/vi/fz-gsWVi9OU/hqdefault.jpg', 'Informational', 1200, 'Get your garden ready for spring with these expert tips!', '2023-03-20 10:00:00', 1, 9, 5);

INSERT INTO youtube.YOUTUBE_VIDEO (TITLE, URL, THUMBNAIL, CATEGORY, DURATION, DESCRIPTION, UPLOAD_DATETIME, IS_TRANSCODING_DONE, CHANNEL_ID, UPLOAD_USER_ID) 
VALUES ('Funny Cats Compilation', 'https://www.youtube.com/watch?v=ABkY3b11Ykw', 'https://i.ytimg.com/vi/ABkY3b11Ykw/hqdefault.jpg', 'Informational', 3600, 'Watch these hilarious cats doing silly things!', '2022-11-03 14:25:00', 0, 4, 9);

INSERT INTO youtube.YOUTUBE_VIDEO (TITLE, URL, THUMBNAIL, CATEGORY, DURATION, DESCRIPTION, UPLOAD_DATETIME, IS_TRANSCODING_DONE, CHANNEL_ID, UPLOAD_USER_ID) 
VALUES ('Yoga for Beginners', 'https://www.youtube.com/watch?v=Jno3pZS-sAk', 'https://i.ytimg.com/vi/Jno3pZS-sAk/hqdefault.jpg', 'Informational', 1800, 'Learn the basics of yoga with this easy-to-follow guide.', '2023-01-01 08:00:00', 1, 7, 6);

INSERT INTO youtube.YOUTUBE_VIDEO (TITLE, URL, THUMBNAIL, CATEGORY, DURATION, DESCRIPTION, UPLOAD_DATETIME, IS_TRANSCODING_DONE, CHANNEL_ID, UPLOAD_USER_ID) 
VALUES ('Cooking with Jamie Oliver', 'https://www.youtube.com/watch?v=5RQn5PJNfL4', 'https://i.ytimg.com/vi/5RQn5PJNfL4/hqdefault.jpg', 'Informational', 2700, 'Join celebrity chef Jamie Oliver as he cooks up a storm in the kitchen!', '2022-12-15 17:30:00', 0, 3, 10);

INSERT INTO youtube.YOUTUBE_VIDEO (TITLE, URL, THUMBNAIL, CATEGORY, DURATION, DESCRIPTION, UPLOAD_DATETIME, IS_TRANSCODING_DONE, CHANNEL_ID, UPLOAD_USER_ID) 
VALUES ('Gardening Tips for Spring', 'https://www.youtube.com/watch?v=fz-gsWVi9OU', 'https://i.ytimg.com/vi/fz-gsWVi9OU/hqdefault.jpg', 'Entertainment', 1200, 'Get your garden ready for spring with these expert tips!', '2023-03-20 10:00:00', 1, 9, 5);


-- INSERT SPONSOR
INSERT INTO `youtube`.`YOUTUBE_SPONSOR` (`SPONSOR_NAME`, `SPONSOR_PHONE_NO`, `SPONSOR_EMAIL`, `SPONSOR_ADDRESS`, `SPONSOR_BANK_ACCOUNT_NO`)
VALUES ('Acme Corp.', '555-1234', 'acme@example.com', '123 Main St., Anytown USA', '12345678901234567890');

INSERT INTO `youtube`.`YOUTUBE_SPONSOR` (`SPONSOR_NAME`, `SPONSOR_PHONE_NO`, `SPONSOR_EMAIL`, `SPONSOR_ADDRESS`, `SPONSOR_BANK_ACCOUNT_NO`)
VALUES ('XYZ Company', '555-5678', 'info@xyzcorp.com', '456 Market St., Anytown USA', '09876543210987654321');

INSERT INTO `youtube`.`YOUTUBE_SPONSOR` (`SPONSOR_NAME`, `SPONSOR_PHONE_NO`, `SPONSOR_EMAIL`, `SPONSOR_ADDRESS`, `SPONSOR_BANK_ACCOUNT_NO`)
VALUES ('Big Bank', '555-2468', 'customerservice@bigbank.com', '789 Broadway, Anytown USA', '24680135792468013579');

INSERT INTO `youtube`.`YOUTUBE_SPONSOR` (`SPONSOR_NAME`, `SPONSOR_PHONE_NO`, `SPONSOR_EMAIL`, `SPONSOR_ADDRESS`, `SPONSOR_BANK_ACCOUNT_NO`)
VALUES ('Acme Widgets', '555-9876', 'sales@acmewidgets.com', '321 Elm St., Anytown USA', '13579246801357924680');

INSERT INTO `youtube`.`YOUTUBE_SPONSOR` (`SPONSOR_NAME`, `SPONSOR_PHONE_NO`, `SPONSOR_EMAIL`, `SPONSOR_ADDRESS`, `SPONSOR_BANK_ACCOUNT_NO`)
VALUES ('Global Enterprises', '555-5555', 'contactus@globale.com', '555 Oak St., Anytown USA', '98765432109876543210');

INSERT INTO `youtube`.`YOUTUBE_SPONSOR` (`SPONSOR_NAME`, `SPONSOR_PHONE_NO`, `SPONSOR_EMAIL`, `SPONSOR_ADDRESS`, `SPONSOR_BANK_ACCOUNT_NO`)
VALUES ('Sunshine Corp.', '555-2468', 'sunshineco@example.com', '1234 Pine St., Anytown USA', '02468135790246813579');

INSERT INTO `youtube`.`YOUTUBE_SPONSOR` (`SPONSOR_NAME`, `SPONSOR_PHONE_NO`, `SPONSOR_EMAIL`, `SPONSOR_ADDRESS`, `SPONSOR_BANK_ACCOUNT_NO`)
VALUES ('Innovative Solutions', '555-1234', 'info@innovativesolutions.com', '567 Maple Ave., Anytown USA', '97531086429753108642');

INSERT INTO `youtube`.`YOUTUBE_SPONSOR` (`SPONSOR_NAME`, `SPONSOR_PHONE_NO`, `SPONSOR_EMAIL`, `SPONSOR_ADDRESS`, `SPONSOR_BANK_ACCOUNT_NO`)
VALUES ('Top Notch Services', '555-5678', 'contact@topnotchservices.com', '890 Oak Ave., Anytown USA', '13579753106897531068');

INSERT INTO `youtube`.`YOUTUBE_SPONSOR` (`SPONSOR_NAME`, `SPONSOR_PHONE_NO`, `SPONSOR_EMAIL`, `SPONSOR_ADDRESS`, `SPONSOR_BANK_ACCOUNT_NO`)
VALUES ('ABC Corporation', '555-123-4567', 'info@abccorp.com', '123 Main St, Anytown USA', '1234567890123456');

INSERT INTO `youtube`.`YOUTUBE_SPONSOR` (`SPONSOR_NAME`, `SPONSOR_PHONE_NO`, `SPONSOR_EMAIL`, `SPONSOR_ADDRESS`, `SPONSOR_BANK_ACCOUNT_NO`)
VALUES ('XYZ Corporation', '555-987-6543', 'info@xyzcorp.com', '456 Oak St, Anytown USA', '2345678901234567');

INSERT INTO `youtube`.`YOUTUBE_SPONSOR` (`SPONSOR_NAME`, `SPONSOR_PHONE_NO`, `SPONSOR_EMAIL`, `SPONSOR_ADDRESS`, `SPONSOR_BANK_ACCOUNT_NO`)
VALUES ('Acme Inc', '555-555-1212', 'info@acmeinc.com', '789 Maple Ave, Anytown USA', '3456789012345678');

INSERT INTO `youtube`.`YOUTUBE_SPONSOR` (`SPONSOR_NAME`, `SPONSOR_PHONE_NO`, `SPONSOR_EMAIL`, `SPONSOR_ADDRESS`, `SPONSOR_BANK_ACCOUNT_NO`)
VALUES ('Beta Corp', '555-555-2323', 'info@betacorp.com', '321 Pine St, Anytown USA', '4567890123456789');

INSERT INTO `youtube`.`YOUTUBE_SPONSOR` (`SPONSOR_NAME`, `SPONSOR_PHONE_NO`, `SPONSOR_EMAIL`, `SPONSOR_ADDRESS`, `SPONSOR_BANK_ACCOUNT_NO`)
VALUES ('Delta Enterprises', '555-555-3434', 'info@deltaent.com', '654 Cedar Rd, Anytown USA', '5678901234567890');

INSERT INTO `youtube`.`YOUTUBE_SPONSOR` (`SPONSOR_NAME`, `SPONSOR_PHONE_NO`, `SPONSOR_EMAIL`, `SPONSOR_ADDRESS`, `SPONSOR_BANK_ACCOUNT_NO`)
VALUES ('Echo Inc', '555-555-4545', 'info@echoinc.com', '987 Elm St, Anytown USA', '6789012345678901');

INSERT INTO `youtube`.`YOUTUBE_SPONSOR` (`SPONSOR_NAME`, `SPONSOR_PHONE_NO`, `SPONSOR_EMAIL`, `SPONSOR_ADDRESS`, `SPONSOR_BANK_ACCOUNT_NO`)
VALUES ('Foxtrot Corp', '555-555-5656', 'info@foxtrotcorp.com', '246 Oak St, Anytown USA', '7890123456789012');

INSERT INTO `youtube`.`YOUTUBE_SPONSOR` (`SPONSOR_NAME`, `SPONSOR_PHONE_NO`, `SPONSOR_EMAIL`, `SPONSOR_ADDRESS`, `SPONSOR_BANK_ACCOUNT_NO`)
VALUES ('Golf Co', '555-555-6767', 'info@golfco.com', '135 Maple Ave, Anytown USA', '8901234567890123');


-- INSERT VIDEO SPONSOR MAPPING
INSERT INTO youtube.YOUTUBE_VIDEO_SPONSOR_MAPPING (SPONSORED_AMOUNT, VIDEO_ID, SPONSOR_ID) VALUES (1000, 1, 1);
INSERT INTO youtube.YOUTUBE_VIDEO_SPONSOR_MAPPING (SPONSORED_AMOUNT, VIDEO_ID, SPONSOR_ID) VALUES (1000, 1, 2);
INSERT INTO youtube.YOUTUBE_VIDEO_SPONSOR_MAPPING (SPONSORED_AMOUNT, VIDEO_ID, SPONSOR_ID) VALUES (1000, 1, 3);
INSERT INTO youtube.YOUTUBE_VIDEO_SPONSOR_MAPPING (SPONSORED_AMOUNT, VIDEO_ID, SPONSOR_ID) VALUES (500, 2, 2);
INSERT INTO youtube.YOUTUBE_VIDEO_SPONSOR_MAPPING (SPONSORED_AMOUNT, VIDEO_ID, SPONSOR_ID) VALUES (750, 3, 3);
INSERT INTO youtube.YOUTUBE_VIDEO_SPONSOR_MAPPING (SPONSORED_AMOUNT, VIDEO_ID, SPONSOR_ID) VALUES (200, 4, 4);
INSERT INTO youtube.YOUTUBE_VIDEO_SPONSOR_MAPPING (SPONSORED_AMOUNT, VIDEO_ID, SPONSOR_ID) VALUES (1500, 5, 5);
INSERT INTO youtube.YOUTUBE_VIDEO_SPONSOR_MAPPING (SPONSORED_AMOUNT, VIDEO_ID, SPONSOR_ID) VALUES (300, 6, 6);
INSERT INTO youtube.YOUTUBE_VIDEO_SPONSOR_MAPPING (SPONSORED_AMOUNT, VIDEO_ID, SPONSOR_ID) VALUES (400, 7, 7);
INSERT INTO youtube.YOUTUBE_VIDEO_SPONSOR_MAPPING (SPONSORED_AMOUNT, VIDEO_ID, SPONSOR_ID) VALUES (100, 8, 8);
INSERT INTO youtube.YOUTUBE_VIDEO_SPONSOR_MAPPING (SPONSORED_AMOUNT, VIDEO_ID, SPONSOR_ID) VALUES (900, 9, 9);
INSERT INTO youtube.YOUTUBE_VIDEO_SPONSOR_MAPPING (SPONSORED_AMOUNT, VIDEO_ID, SPONSOR_ID) VALUES (1200, 10, 10);

-- INSERT LIKES DATA
INSERT INTO `youtube`.`YOUTUBE_LIKES` (`USER_ID`, `VIDEO_ID`, `LIKE_DATETIME`) VALUES (1, 2, '2022-11-02 12:34:56');
INSERT INTO `youtube`.`YOUTUBE_LIKES` (`USER_ID`, `VIDEO_ID`, `LIKE_DATETIME`) VALUES (2, 9, '2022-11-03 10:20:30');
INSERT INTO `youtube`.`YOUTUBE_LIKES` (`USER_ID`, `VIDEO_ID`, `LIKE_DATETIME`) VALUES (3, 4, '2022-11-04 15:16:17');
INSERT INTO `youtube`.`YOUTUBE_LIKES` (`USER_ID`, `VIDEO_ID`, `LIKE_DATETIME`) VALUES (4, 12, '2022-11-05 09:08:07');
INSERT INTO `youtube`.`YOUTUBE_LIKES` (`USER_ID`, `VIDEO_ID`, `LIKE_DATETIME`) VALUES (5, 5, '2022-11-06 18:22:44');
INSERT INTO `youtube`.`YOUTUBE_LIKES` (`USER_ID`, `VIDEO_ID`, `LIKE_DATETIME`) VALUES (6, 8, '2022-11-07 14:55:12');
INSERT INTO `youtube`.`YOUTUBE_LIKES` (`USER_ID`, `VIDEO_ID`, `LIKE_DATETIME`) VALUES (7, 14, '2022-11-08 20:12:34');
INSERT INTO `youtube`.`YOUTUBE_LIKES` (`USER_ID`, `VIDEO_ID`, `LIKE_DATETIME`) VALUES (8, 1, '2022-11-09 16:25:18');
INSERT INTO `youtube`.`YOUTUBE_LIKES` (`USER_ID`, `VIDEO_ID`, `LIKE_DATETIME`) VALUES (9, 10, '2022-11-10 11:44:55');
INSERT INTO `youtube`.`YOUTUBE_LIKES` (`USER_ID`, `VIDEO_ID`, `LIKE_DATETIME`) VALUES (10, 16, '2022-11-11 08:30:00');
INSERT INTO `youtube`.`YOUTUBE_LIKES` (`USER_ID`, `VIDEO_ID`, `LIKE_DATETIME`) VALUES (1, 19, '2022-11-02 12:34:56');
INSERT INTO `youtube`.`YOUTUBE_LIKES` (`USER_ID`, `VIDEO_ID`, `LIKE_DATETIME`) VALUES (2, 20, '2022-11-03 10:20:30');
INSERT INTO `youtube`.`YOUTUBE_LIKES` (`USER_ID`, `VIDEO_ID`, `LIKE_DATETIME`) VALUES (3, 21, '2022-11-04 15:16:17');
INSERT INTO `youtube`.`YOUTUBE_LIKES` (`USER_ID`, `VIDEO_ID`, `LIKE_DATETIME`) VALUES (4, 19, '2022-11-05 09:08:07');
INSERT INTO `youtube`.`YOUTUBE_LIKES` (`USER_ID`, `VIDEO_ID`, `LIKE_DATETIME`) VALUES (5, 20, '2022-11-06 18:22:44');
INSERT INTO `youtube`.`YOUTUBE_LIKES` (`USER_ID`, `VIDEO_ID`, `LIKE_DATETIME`) VALUES (5, 27, '2022-11-06 18:22:44');

-- INSERT HISTORY DATA
INSERT INTO `youtube`.`YOUTUBE_HISTORY` (`WATCH_TIMESTAMP`, `USER_ID`, `VIDEO_ID`) VALUES ('2022-11-02 12:34:56', 1, 2);
INSERT INTO `youtube`.`YOUTUBE_HISTORY` (`WATCH_TIMESTAMP`, `USER_ID`, `VIDEO_ID`) VALUES ('2022-11-03 10:20:30', 2, 9);
INSERT INTO `youtube`.`YOUTUBE_HISTORY` (`WATCH_TIMESTAMP`, `USER_ID`, `VIDEO_ID`) VALUES ('2022-11-04 15:16:17', 3, 4);
INSERT INTO `youtube`.`YOUTUBE_HISTORY` (`WATCH_TIMESTAMP`, `USER_ID`, `VIDEO_ID`) VALUES ('2022-11-05 09:08:07', 4, 12);
INSERT INTO `youtube`.`YOUTUBE_HISTORY` (`WATCH_TIMESTAMP`, `USER_ID`, `VIDEO_ID`) VALUES ('2022-11-06 18:22:44', 5, 5);
INSERT INTO `youtube`.`YOUTUBE_HISTORY` (`WATCH_TIMESTAMP`, `USER_ID`, `VIDEO_ID`) VALUES ('2022-11-07 14:55:12', 6, 8);
INSERT INTO `youtube`.`YOUTUBE_HISTORY` (`WATCH_TIMESTAMP`, `USER_ID`, `VIDEO_ID`) VALUES ('2022-11-08 20:12:34', 7, 14);
INSERT INTO `youtube`.`YOUTUBE_HISTORY` (`WATCH_TIMESTAMP`, `USER_ID`, `VIDEO_ID`) VALUES ('2022-11-09 16:25:18', 8, 1);
INSERT INTO `youtube`.`YOUTUBE_HISTORY` (`WATCH_TIMESTAMP`, `USER_ID`, `VIDEO_ID`) VALUES ('2022-11-10 11:44:55', 9, 10);
INSERT INTO `youtube`.`YOUTUBE_HISTORY` (`WATCH_TIMESTAMP`, `USER_ID`, `VIDEO_ID`) VALUES ('2022-11-11 08:30:00', 10, 16);
INSERT INTO `youtube`.`YOUTUBE_HISTORY` (`WATCH_TIMESTAMP`, `USER_ID`, `VIDEO_ID`) VALUES ('2022-11-02 12:34:56', 1, 19);
INSERT INTO `youtube`.`YOUTUBE_HISTORY` (`WATCH_TIMESTAMP`, `USER_ID`, `VIDEO_ID`) VALUES ('2022-11-03 10:20:30', 2, 20);
INSERT INTO `youtube`.`YOUTUBE_HISTORY` (`WATCH_TIMESTAMP`, `USER_ID`, `VIDEO_ID`) VALUES ('2022-11-04 15:16:17', 3, 21);
INSERT INTO `youtube`.`YOUTUBE_HISTORY` (`WATCH_TIMESTAMP`, `USER_ID`, `VIDEO_ID`) VALUES ('2022-11-05 09:08:07', 4, 19);
INSERT INTO `youtube`.`YOUTUBE_HISTORY` (`WATCH_TIMESTAMP`, `USER_ID`, `VIDEO_ID`) VALUES ('2022-11-06 18:22:44', 5, 20);
INSERT INTO `youtube`.`YOUTUBE_HISTORY` (`WATCH_TIMESTAMP`, `USER_ID`, `VIDEO_ID`) VALUES ('2022-11-07 14:55:12', 6, 21);
INSERT INTO `youtube`.`YOUTUBE_HISTORY` (`WATCH_TIMESTAMP`, `USER_ID`, `VIDEO_ID`) VALUES ('2022-11-08 20:12:34', 7, 19);
INSERT INTO `youtube`.`YOUTUBE_HISTORY` (`WATCH_TIMESTAMP`, `USER_ID`, `VIDEO_ID`) VALUES ('2022-11-09 16:25:18', 8, 20);
INSERT INTO `youtube`.`YOUTUBE_HISTORY` (`WATCH_TIMESTAMP`, `USER_ID`, `VIDEO_ID`) VALUES ('2022-11-10 11:44:55', 9, 21);
INSERT INTO `youtube`.`YOUTUBE_HISTORY` (`WATCH_TIMESTAMP`, `USER_ID`, `VIDEO_ID`) VALUES ('2022-11-11 08:30:00', 10, 19);
INSERT INTO `youtube`.`YOUTUBE_HISTORY` (`WATCH_TIMESTAMP`, `USER_ID`, `VIDEO_ID`) VALUES ('2022-11-07 14:55:12', 6, 22);
INSERT INTO `youtube`.`YOUTUBE_HISTORY` (`WATCH_TIMESTAMP`, `USER_ID`, `VIDEO_ID`) VALUES ('2022-11-08 20:12:34', 7, 23);
INSERT INTO `youtube`.`YOUTUBE_HISTORY` (`WATCH_TIMESTAMP`, `USER_ID`, `VIDEO_ID`) VALUES ('2022-11-09 16:25:18', 8, 22);
INSERT INTO `youtube`.`YOUTUBE_HISTORY` (`WATCH_TIMESTAMP`, `USER_ID`, `VIDEO_ID`) VALUES ('2022-11-10 11:44:55', 9, 22);
INSERT INTO `youtube`.`YOUTUBE_HISTORY` (`WATCH_TIMESTAMP`, `USER_ID`, `VIDEO_ID`) VALUES ('2022-11-11 08:30:00', 10, 24);
INSERT INTO `youtube`.`YOUTUBE_HISTORY` (`WATCH_TIMESTAMP`, `USER_ID`, `VIDEO_ID`) VALUES ('2022-11-11 08:30:00', 10, 28);

-- INSERT SUBSCRIPTION DATA
INSERT INTO `youtube`.`YOUTUBE_SUBSCRIPTION` (`SUBSCRIPTION_RECORD_ID`, `IS_PAID_SUBSCRIPTION`, `CHANNEL_ID`, `USER_ID`) VALUES (1, TRUE, 11, 1);
INSERT INTO `youtube`.`YOUTUBE_SUBSCRIPTION` (`SUBSCRIPTION_RECORD_ID`, `IS_PAID_SUBSCRIPTION`, `CHANNEL_ID`, `USER_ID`) VALUES (2, TRUE, 11, 2);
INSERT INTO `youtube`.`YOUTUBE_SUBSCRIPTION` (`SUBSCRIPTION_RECORD_ID`, `IS_PAID_SUBSCRIPTION`, `CHANNEL_ID`, `USER_ID`) VALUES (3, TRUE, 11, 3);
INSERT INTO `youtube`.`YOUTUBE_SUBSCRIPTION` (`SUBSCRIPTION_RECORD_ID`, `IS_PAID_SUBSCRIPTION`, `CHANNEL_ID`, `USER_ID`) VALUES (4, TRUE, 11, 4);
INSERT INTO `youtube`.`YOUTUBE_SUBSCRIPTION` (`SUBSCRIPTION_RECORD_ID`, `IS_PAID_SUBSCRIPTION`, `CHANNEL_ID`, `USER_ID`) VALUES (5, TRUE, 10, 5);
INSERT INTO `youtube`.`YOUTUBE_SUBSCRIPTION` (`SUBSCRIPTION_RECORD_ID`, `IS_PAID_SUBSCRIPTION`, `CHANNEL_ID`, `USER_ID`) VALUES (6, TRUE, 11, 6);
INSERT INTO `youtube`.`YOUTUBE_SUBSCRIPTION` (`SUBSCRIPTION_RECORD_ID`, `IS_PAID_SUBSCRIPTION`, `CHANNEL_ID`, `USER_ID`) VALUES (7, TRUE, 1, 7);
INSERT INTO `youtube`.`YOUTUBE_SUBSCRIPTION` (`SUBSCRIPTION_RECORD_ID`, `IS_PAID_SUBSCRIPTION`, `CHANNEL_ID`, `USER_ID`) VALUES (8, FALSE, 2, 8);
INSERT INTO `youtube`.`YOUTUBE_SUBSCRIPTION` (`SUBSCRIPTION_RECORD_ID`, `IS_PAID_SUBSCRIPTION`, `CHANNEL_ID`, `USER_ID`) VALUES (9, TRUE, 5, 9);
INSERT INTO `youtube`.`YOUTUBE_SUBSCRIPTION` (`SUBSCRIPTION_RECORD_ID`, `IS_PAID_SUBSCRIPTION`, `CHANNEL_ID`, `USER_ID`) VALUES (10, FALSE, 7, 10);
INSERT INTO `youtube`.`YOUTUBE_SUBSCRIPTION` (`SUBSCRIPTION_RECORD_ID`, `IS_PAID_SUBSCRIPTION`, `CHANNEL_ID`, `USER_ID`) VALUES (11, TRUE, 9, 1);
INSERT INTO `youtube`.`YOUTUBE_SUBSCRIPTION` (`SUBSCRIPTION_RECORD_ID`, `IS_PAID_SUBSCRIPTION`, `CHANNEL_ID`, `USER_ID`) VALUES (12, FALSE, 11, 2);
INSERT INTO `youtube`.`YOUTUBE_SUBSCRIPTION` (`SUBSCRIPTION_RECORD_ID`, `IS_PAID_SUBSCRIPTION`, `CHANNEL_ID`, `USER_ID`) VALUES (13, TRUE, 11, 3);
INSERT INTO `youtube`.`YOUTUBE_SUBSCRIPTION` (`SUBSCRIPTION_RECORD_ID`, `IS_PAID_SUBSCRIPTION`, `CHANNEL_ID`, `USER_ID`) VALUES (14, FALSE, 1, 4);
INSERT INTO `youtube`.`YOUTUBE_SUBSCRIPTION` (`SUBSCRIPTION_RECORD_ID`, `IS_PAID_SUBSCRIPTION`, `CHANNEL_ID`, `USER_ID`) VALUES (15, TRUE, 2, 5);
INSERT INTO `youtube`.`YOUTUBE_SUBSCRIPTION` (`SUBSCRIPTION_RECORD_ID`, `IS_PAID_SUBSCRIPTION`, `CHANNEL_ID`, `USER_ID`) VALUES (16, FALSE, 4, 6);
INSERT INTO `youtube`.`YOUTUBE_SUBSCRIPTION` (`SUBSCRIPTION_RECORD_ID`, `IS_PAID_SUBSCRIPTION`, `CHANNEL_ID`, `USER_ID`) VALUES (17, FALSE, 12, 6);


-- INSERT KEYWORDS DATA
INSERT INTO youtube.YOUTUBE_KEYWORDS (KEYWORD_NAME) VALUES ('music');
INSERT INTO youtube.YOUTUBE_KEYWORDS (KEYWORD_NAME) VALUES ('cooking');
INSERT INTO youtube.YOUTUBE_KEYWORDS (KEYWORD_NAME) VALUES ('gaming');
INSERT INTO youtube.YOUTUBE_KEYWORDS (KEYWORD_NAME) VALUES ('travel');
INSERT INTO youtube.YOUTUBE_KEYWORDS (KEYWORD_NAME) VALUES ('fashion');
INSERT INTO youtube.YOUTUBE_KEYWORDS (KEYWORD_NAME) VALUES ('beauty');
INSERT INTO youtube.YOUTUBE_KEYWORDS (KEYWORD_NAME) VALUES ('comedy');
INSERT INTO youtube.YOUTUBE_KEYWORDS (KEYWORD_NAME) VALUES ('education');
INSERT INTO youtube.YOUTUBE_KEYWORDS (KEYWORD_NAME) VALUES ('sports');
INSERT INTO youtube.YOUTUBE_KEYWORDS (KEYWORD_NAME) VALUES ('technology');

-- INSERT KEYWORDS VIDEO MAPPING DATA
INSERT INTO youtube.YOUTUBE_KEYWORD_VIDEO_MAPPING (VIDEO_ID, KEYWORD_ID, ASSIGNED_DATE_TIME) VALUES (1, 1, NOW());
INSERT INTO youtube.YOUTUBE_KEYWORD_VIDEO_MAPPING (VIDEO_ID, KEYWORD_ID, ASSIGNED_DATE_TIME) VALUES (2, 2, NOW());
INSERT INTO youtube.YOUTUBE_KEYWORD_VIDEO_MAPPING (VIDEO_ID, KEYWORD_ID, ASSIGNED_DATE_TIME) VALUES (3, 3, NOW());
INSERT INTO youtube.YOUTUBE_KEYWORD_VIDEO_MAPPING (VIDEO_ID, KEYWORD_ID, ASSIGNED_DATE_TIME) VALUES (4, 4, NOW());
INSERT INTO youtube.YOUTUBE_KEYWORD_VIDEO_MAPPING (VIDEO_ID, KEYWORD_ID, ASSIGNED_DATE_TIME) VALUES (5, 5, NOW());
INSERT INTO youtube.YOUTUBE_KEYWORD_VIDEO_MAPPING (VIDEO_ID, KEYWORD_ID, ASSIGNED_DATE_TIME) VALUES (6, 6, NOW());
INSERT INTO youtube.YOUTUBE_KEYWORD_VIDEO_MAPPING (VIDEO_ID, KEYWORD_ID, ASSIGNED_DATE_TIME) VALUES (7, 7, NOW());
INSERT INTO youtube.YOUTUBE_KEYWORD_VIDEO_MAPPING (VIDEO_ID, KEYWORD_ID, ASSIGNED_DATE_TIME) VALUES (8, 8, NOW());
INSERT INTO youtube.YOUTUBE_KEYWORD_VIDEO_MAPPING (VIDEO_ID, KEYWORD_ID, ASSIGNED_DATE_TIME) VALUES (9, 9, NOW());
INSERT INTO youtube.YOUTUBE_KEYWORD_VIDEO_MAPPING (VIDEO_ID, KEYWORD_ID, ASSIGNED_DATE_TIME) VALUES (10, 10, NOW());

-- INSERT COMMENTS DATA
INSERT INTO youtube.YOUTUBE_COMMENTS (TEXT, COMMENT_DATETIME, SENTIMENTS, NO_OF_LIKES, VIDEO_ID, USER_ID) 
VALUES ('Great video! I learned a lot from this.', '2022-08-01 10:15:00', 0.9, 10, 1, 1);

INSERT INTO youtube.YOUTUBE_COMMENTS (TEXT, COMMENT_DATETIME, SENTIMENTS, NO_OF_LIKES, VIDEO_ID, USER_ID) 
VALUES ('The information in this video is really helpful.', '2022-08-02 12:30:00', 0.85, 12, 1, 2);

INSERT INTO youtube.YOUTUBE_COMMENTS (TEXT, COMMENT_DATETIME, SENTIMENTS, NO_OF_LIKES, VIDEO_ID, USER_ID) 
VALUES ('I loved this video! Please keep making more like this.', '2022-08-03 15:45:00', 0.95, 8, 1, 3);

INSERT INTO youtube.YOUTUBE_COMMENTS (TEXT, COMMENT_DATETIME, SENTIMENTS, NO_OF_LIKES, VIDEO_ID, USER_ID) 
VALUES ('This video is not helpful at all.', '2022-08-04 18:00:00', 0.2, 2, 2, 4);

INSERT INTO youtube.YOUTUBE_COMMENTS (TEXT, COMMENT_DATETIME, SENTIMENTS, NO_OF_LIKES, VIDEO_ID, USER_ID) 
VALUES ('I disagree with some of the points made in this video.', '2022-08-05 20:15:00', 0.6, 5, 2, 5);

INSERT INTO youtube.YOUTUBE_COMMENTS (TEXT, COMMENT_DATETIME, SENTIMENTS, NO_OF_LIKES, VIDEO_ID, USER_ID) 
VALUES ('This video was really boring.', '2022-08-06 22:30:00', 0.3, 1, 3, 6);

INSERT INTO youtube.YOUTUBE_COMMENTS (TEXT, COMMENT_DATETIME, SENTIMENTS, NO_OF_LIKES, VIDEO_ID, USER_ID) 
VALUES ('The presenter in this video speaks too quickly.', '2022-08-07 00:45:00', 0.4, 3, 3, 7);

INSERT INTO youtube.YOUTUBE_COMMENTS (TEXT, COMMENT_DATETIME, SENTIMENTS, NO_OF_LIKES, VIDEO_ID, USER_ID) 
VALUES ('I found this video to be very informative.', '2022-08-08 03:00:00', 0.8, 7, 4, 8);

INSERT INTO youtube.YOUTUBE_COMMENTS (TEXT, COMMENT_DATETIME, SENTIMENTS, NO_OF_LIKES, VIDEO_ID, USER_ID) 
VALUES ('This video was too short.', '2022-08-09 05:15:00', 0.5, 4, 4, 9);

INSERT INTO youtube.YOUTUBE_COMMENTS (TEXT, COMMENT_DATETIME, SENTIMENTS, NO_OF_LIKES, VIDEO_ID, USER_ID)
VALUES ('Great video!', '2022-01-01 12:00:00', 0.8, 10, 15, 7);

INSERT INTO youtube.YOUTUBE_COMMENTS (TEXT, COMMENT_DATETIME, SENTIMENTS, NO_OF_LIKES, VIDEO_ID, USER_ID)
VALUES ('Thanks for sharing', '2022-01-02 15:30:00', 0.9, 5, 14, 6);

INSERT INTO youtube.YOUTUBE_COMMENTS (TEXT, COMMENT_DATETIME, SENTIMENTS, NO_OF_LIKES, VIDEO_ID, USER_ID)
VALUES ('This video sucks', '2022-01-03 09:45:00', 0.2, 2, 12, 5);

INSERT INTO youtube.YOUTUBE_COMMENTS (TEXT, COMMENT_DATETIME, SENTIMENTS, NO_OF_LIKES, VIDEO_ID, USER_ID)
VALUES ('Amazing content', '2022-01-04 20:00:00', 1.0, 20, 19, 11);

INSERT INTO youtube.YOUTUBE_COMMENTS (TEXT, COMMENT_DATETIME, SENTIMENTS, NO_OF_LIKES, VIDEO_ID, USER_ID)
VALUES ('I learned so much from this video', '2022-01-05 13:15:00', 0.95, 12, 16, 8);

INSERT INTO youtube.YOUTUBE_COMMENTS (TEXT, COMMENT_DATETIME, SENTIMENTS, NO_OF_LIKES, VIDEO_ID, USER_ID)
VALUES ('Not bad, but could be better', '2022-01-06 10:30:00', 0.6, 3, 10, 5);

INSERT INTO youtube.YOUTUBE_COMMENTS (TEXT, COMMENT_DATETIME, SENTIMENTS, NO_OF_LIKES, VIDEO_ID, USER_ID)
VALUES ('This video is a waste of time', '2022-01-07 16:45:00', 0.1, 1, 13, 7);

INSERT INTO youtube.YOUTUBE_COMMENTS (TEXT, COMMENT_DATETIME, SENTIMENTS, NO_OF_LIKES, VIDEO_ID, USER_ID)
VALUES ('One of the best videos I have seen', '2022-01-08 19:00:00', 0.98, 18, 20, 9);

INSERT INTO youtube.YOUTUBE_COMMENTS (TEXT, COMMENT_DATETIME, SENTIMENTS, NO_OF_LIKES, VIDEO_ID, USER_ID)
VALUES ('I did not find this video helpful', '2022-01-10 14:15:00', 0.3, 2, 11, 6);

INSERT INTO youtube.YOUTUBE_COMMENTS (TEXT, COMMENT_DATETIME, SENTIMENTS, NO_OF_LIKES, VIDEO_ID, USER_ID)
VALUES ('Wow', '2022-01-05 13:15:00', 0.95, 12, 22, 8);

INSERT INTO youtube.YOUTUBE_COMMENTS (TEXT, COMMENT_DATETIME, SENTIMENTS, NO_OF_LIKES, VIDEO_ID, USER_ID)
VALUES ('xoxo', '2022-01-06 10:30:00', 0.6, 3, 23, 5);

INSERT INTO youtube.YOUTUBE_COMMENTS (TEXT, COMMENT_DATETIME, SENTIMENTS, NO_OF_LIKES, VIDEO_ID, USER_ID)
VALUES ('We love katy perry', '2022-01-07 16:45:00', 0.1, 1, 22, 7);

INSERT INTO youtube.YOUTUBE_COMMENTS (TEXT, COMMENT_DATETIME, SENTIMENTS, NO_OF_LIKES, VIDEO_ID, USER_ID)
VALUES ('great !', '2022-01-08 19:00:00', 0.98, 18, 22, 9);

INSERT INTO youtube.YOUTUBE_COMMENTS (TEXT, COMMENT_DATETIME, SENTIMENTS, NO_OF_LIKES, VIDEO_ID, USER_ID)
VALUES ('nice !', '2022-01-10 14:15:00', 0.3, 2, 24, 6);

INSERT INTO youtube.YOUTUBE_COMMENTS (TEXT, COMMENT_DATETIME, SENTIMENTS, NO_OF_LIKES, VIDEO_ID, USER_ID)
VALUES ('good !', '2022-01-10 14:15:00', 0.8, 2, 24, 7);

INSERT INTO youtube.YOUTUBE_COMMENTS (TEXT, COMMENT_DATETIME, SENTIMENTS, NO_OF_LIKES, VIDEO_ID, USER_ID)
VALUES ('so good !', '2022-01-10 14:15:00', 0.2, 2, 24, 8);
